// Collect the Astro source's CSS into one stylesheet for the Next build.
//
// Order: global.css (with its @imports inlined), then every component's
// <style> block: components, ui, sections, layouts, pages. Comments are kept.
// The Fontsource stylesheets are imported separately by next/src/app/layout.tsx,
// ahead of this file, in the same order Base.astro imports them.
//
// Astro scopes component styles; one flat file does not. So every component's
// selectors must start with a class only that component uses. The script
// refuses to write the file when a root class appears in two components, or
// when a component restyles a class from global.css, since that is exactly
// where one component would start restyling another. :global(x) is unwrapped
// to x: flattening makes every selector global, which is what it asked for.
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const A = join(ROOT, 'src');
const OUT = join(ROOT, 'next', 'src', 'styles', 'site.css');
const walk = (d) => readdirSync(d).flatMap((f) => (statSync(join(d, f)).isDirectory() ? walk(join(d, f)) : [join(d, f)]));

function inline(file) {
  return readFileSync(file, 'utf8').replace(/@import\s+['"](.+?)['"];?/g, (_, p) => inline(join(dirname(file), p)));
}

// Unwrap :global(...) with balanced parentheses.
function unglobal(css) {
  let out = '', i = 0;
  for (;;) {
    const at = css.indexOf(':global(', i);
    if (at < 0) return out + css.slice(i);
    out += css.slice(i, at);
    let depth = 1, j = at + 8;
    for (; j < css.length && depth; j++) { if (css[j] === '(') depth++; else if (css[j] === ')') depth--; }
    out += css.slice(at + 8, j - 1);
    i = j;
  }
}

const globalCss = inline(join(A, 'styles', 'global.css'));
const globalClasses = new Set([...globalCss.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/\.([A-Za-z_][\w-]*)/g)].map((m) => m[1]));

const ORDER = ['components/ui', 'components/sections', 'components', 'layouts', 'pages'];
const files = walk(A).filter((f) => f.endsWith('.astro'))
  .map((f) => relative(A, f).replace(/\\/g, '/'))
  .sort((a, b) => {
    const ia = ORDER.findIndex((o) => a.startsWith(o + '/')), ib = ORDER.findIndex((o) => b.startsWith(o + '/'));
    return ia - ib || a.localeCompare(b);
  });

const owners = new Map();
const keyframes = new Map();
const problems = [];
const parts = ['/* GENERATED by tools/collect-css.mjs from the Astro source. Edit the .astro files, then regenerate. */', globalCss.trim()];

for (const rel of files) {
  const src = readFileSync(join(A, rel), 'utf8');
  const blocks = [...src.matchAll(/<style(\s[^>]*)?>([\s\S]*?)<\/style>/g)];
  if (!blocks.length) continue;
  for (const [, attrs = '', raw] of blocks) {
    if (/is:global|define:vars|is:inline/.test(attrs)) problems.push(`${rel}: <style${attrs}> is not allowed`);
    const css = unglobal(raw);
    const bare = css.replace(/\/\*[\s\S]*?\*\//g, '');
    for (const m of bare.matchAll(/@keyframes\s+([\w-]+)/g)) {
      const prev = keyframes.get(m[1]);
      if (prev && prev !== rel) problems.push(`@keyframes ${m[1]} is defined in both ${prev} and ${rel}`);
      else keyframes.set(m[1], rel);
    }
    // Root class of every selector (the first .class it contains).
    for (const m of bare.matchAll(/(?<=^|[{};])([^{};]+)\{/g)) {
      const sel = m[1].trim();
      if (!sel || /^(from|to|\d+%)/.test(sel) || sel.startsWith('@')) continue;
      for (const one of sel.split(',')) {
        const s = one.trim();
        if (!s || /^(from|to|\d+%)$/.test(s)) continue;
        // The first compound selector must carry a class (".x", ".x:hover", ".x[hidden]").
        const cls = s.split(/\s*[\s>+~]\s*/)[0].match(/\.([A-Za-z_][\w-]*)/);
        if (!cls) { problems.push(`${rel}: selector does not start with a component class: "${s}"`); continue; }
        const root = cls[1];
        if (globalClasses.has(root)) { problems.push(`${rel}: restyles global class .${root} in "${s}"`); continue; }
        const prev = owners.get(root);
        if (prev && prev !== rel) problems.push(`.${root} is styled in both ${prev} and ${rel}`);
        else owners.set(root, rel);
      }
    }
    parts.push(`/* ---- ${rel} ---- */\n${css.trim()}`);
  }
}

if (problems.length) {
  console.error('collect-css refused:\n  ' + [...new Set(problems)].join('\n  '));
  process.exit(1);
}
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, parts.join('\n\n') + '\n');
console.log(`${files.length} components scanned -> ${relative(ROOT, OUT)}`);
